language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
    - develop
before_script:
  - chmod a+x dotnet-build.sh
  - chmod a+x build.sh
  - chmod a+x after-success.sh
  - chmod a+x dotnet-test.sh
script:
  - ./dotnet-build.sh
  - ./dotnet-test.sh
  - ./build.sh
after_success:
  - ./after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
